// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqEKVY7wGXBUZ8abna9YbABwr13Y036A',
    appId: '1:450783170369:web:cddf5dd0704774ee021bc0',
    messagingSenderId: '450783170369',
    projectId: 'hospitalapp-3fd3c',
    authDomain: 'hospitalapp-3fd3c.firebaseapp.com',
    storageBucket: 'hospitalapp-3fd3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwPvdSvcKia1_g5Ko3Ie4hLFGtIbp4b4',
    appId: '1:450783170369:android:32d59bf865b8879a021bc0',
    messagingSenderId: '450783170369',
    projectId: 'hospitalapp-3fd3c',
    storageBucket: 'hospitalapp-3fd3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvi_ugXkfKa-yS3lTF9HZ5V8XMfbHQCI',
    appId: '1:450783170369:ios:bc277534416a2e58021bc0',
    messagingSenderId: '450783170369',
    projectId: 'hospitalapp-3fd3c',
    storageBucket: 'hospitalapp-3fd3c.appspot.com',
    iosClientId: '450783170369-6jr1d8r16eh63p652b4k9t62rvcoi9b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvi_ugXkfKa-yS3lTF9HZ5V8XMfbHQCI',
    appId: '1:450783170369:ios:bc277534416a2e58021bc0',
    messagingSenderId: '450783170369',
    projectId: 'hospitalapp-3fd3c',
    storageBucket: 'hospitalapp-3fd3c.appspot.com',
    iosClientId: '450783170369-6jr1d8r16eh63p652b4k9t62rvcoi9b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospital',
  );
}
